version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  dockerize:
    image: jwilder/dockerize