name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker-compose
        run: docker-compose -f docker-compose.prod.yml up -d app elasticsearch

      - name: Copy .env
        run: docker exec -t app cp /home/node/app/.env.example /home/node/app/.env

      - name: Waiting for containers
        run: >-
          docker-compose -f docker-compose.prod.yml run dockerize dockerize
          -wait http://elasticsearch:9200/ -wait http://app:3000/ -timeout 480s

      - name: Run tests
        run: docker exec -t app npm test

      - name: Run build
        run: docker exec -t app npm build